# Generated by Django 5.0.7 on 2024-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
